name: Cypress E2E Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cypress-run:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Start the application
        run: npm start &
        env:
          CI: true

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: http://localhost:3000
          timeout: 60

      - name: Run Cypress tests
        run: npx cypress run
        env:
          CI: true
